<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Destination;
use App\Models\DestinationDetail;
use App\Models\DestinationPhoto;

class DestinationSeeder extends Seeder
{
  public function run(): void
  {
    $jeju = Destination::create([
      'title' => 'Jeju Island Paradise - 5D4N Nature Explorer',
      'slug' => 'jeju-island-paradise-tour',
      'description' => 'Embark on an unforgettable journey to Jeju Island, South Korea\'s premier natural paradise. This 5-day adventure takes you through UNESCO World Heritage sites, pristine beaches, dramatic volcanic landscapes, and unique cultural experiences. Hike the majestic Hallasan Mountain, witness the sunrise at Seongsan Ilchulbong Peak, explore mysterious lava caves, and immerse yourself in Jeju\'s rich traditions. Perfect for nature lovers, adventure seekers, and photography enthusiasts looking to capture breathtaking landscapes and create lasting memories in one of Asia\'s most beautiful destinations.',
      'country' => 'South Korea',
      'city' => 'Jeju',
      'price' => 8500000,
      'date_started' => '2025-12-01',
      'date_ended' => '2025-12-05',
      'type' => 'Nature & Adventure',
      'view_count' => 250,
      'featured_photo' => 'destinations/jeju-featured.jpg',
      'min_people' => 2,
      'max_people' => 15,
    ]);

    DestinationDetail::create([
      'destination_id' => $jeju->id,
      'itinerary' => json_encode([
        'Day 1 - Arrival & Cultural Introduction' => 'Welcome to Jeju! Upon arrival at Jeju International Airport at 10:00 AM, our friendly guide will greet you and transfer you to your hotel. After check-in and refreshment, begin your Jeju adventure with a visit to Dongmun Traditional Market, the island\'s oldest and largest market where you can sample fresh seafood, local delicacies, and shop for unique souvenirs. In the evening, enjoy a welcome dinner featuring Jeju black pork BBQ and fresh seafood. Overnight at 4-star beachfront resort.',
        
        'Day 2 - Hallasan Mountain & Folk Heritage' => 'Early morning departure (7:00 AM) to conquer Hallasan Mountain, South Korea\'s highest peak at 1,950 meters. Choose between the challenging summit trail (8-9 hours) or the easier Eorimok trail (4-5 hours) through pristine forests and volcanic rock formations. After the hike, visit Jeju Folk Village Museum, a living museum showcasing traditional Jeju architecture and lifestyle from the 19th century. Experience traditional crafts, watch cultural performances, and learn about Jeju\'s unique heritage. Dinner features traditional Jeju cuisine with locally-sourced ingredients. Return to hotel around 8:00 PM.',
        
        'Day 3 - Sunrise Peak & Lava Caves' => 'Pre-dawn departure (4:30 AM) to witness the spectacular sunrise from Seongsan Ilchulbong (Sunrise Peak), a UNESCO World Heritage site formed by volcanic eruptions 5,000 years ago. The 30-minute hike to the crater rim rewards you with panoramic views of the ocean and surrounding landscape. Afterward, explore Manjanggul Cave, one of the world\'s longest lava tubes stretching 7.4 km. Marvel at unique lava formations, stalactites, and the massive 7.6-meter lava column. Afternoon free time at Hamdeok Beach for swimming and relaxation. Evening sunset viewing at Woljeongri Beach. Dinner at beachside restaurant.',
        
        'Day 4 - Cultural Parks & Shopping' => 'Visit the whimsical Loveland sculpture park (adults only), followed by the adorable Teddy Bear Museum housing the world\'s largest collection of teddy bears in themed exhibitions. Explore Jungmun Beach and the nearby Jeongbang Waterfall, the only waterfall in Asia that falls directly into the ocean. Afternoon shopping at Jungmun Tourist Complex and local boutiques for Jeju specialties: hallabong citrus, chocolate, cosmetics, and handicrafts. Optional activities: submarine tour or horseback riding (additional cost). Farewell dinner with traditional Jeju performance. Free evening to explore Seogwipo night market.',
        
        'Day 5 - Leisure & Departure' => 'Free morning for personal activities - options include beach walk, hotel spa facilities, or last-minute shopping. Late check-out at 12:00 PM. Transfer to Jeju International Airport for 6:00 PM departure. End of memorable Jeju adventure with hearts full of beautiful memories!',
      ]),
      'arrival' => 'Meet at Jeju International Airport (CJU) Terminal 1, Arrival Hall Gate 3 at 10:00 AM. Look for ACP Tours guide holding company sign with your name. Please provide flight details 48 hours before departure. Emergency contact: +82-64-XXX-XXXX',
      'departure' => 'Check-out from hotel at 12:00 PM on Day 5. Transfer to Jeju International Airport (CJU) for 6:00 PM departure. Please arrive at airport 2 hours before international flights, 1 hour before domestic flights. Late check-out available upon request (additional charge).',
      'tnc' => 'BOOKING & PAYMENT: 30% deposit required to confirm booking. Full payment due 14 days before departure. CANCELLATION POLICY: 30+ days before: 90% refund (10% admin fee). 15-29 days: 50% refund. 7-14 days: 25% refund. Less than 7 days: No refund. FORCE MAJEURE: Full refund if tour cancelled due to natural disasters, government restrictions, or airline cancellations. HEALTH: Travel insurance strongly recommended. Participants must be physically fit for hiking activities. WEATHER: Itinerary may be adjusted due to weather conditions without reducing planned attractions. REQUIREMENTS: Valid passport (6+ months validity), visa if required, comfortable hiking shoes, weather-appropriate clothing.',
      'include' => '4 nights accommodation at 4-star beachfront resort (twin/double sharing). Daily breakfast buffet (Days 2-5). Airport transfers in air-conditioned vehicle. Professional English-speaking tour guide throughout. All entrance fees: Hallasan National Park, Seongsan Ilchulbong, Manjanggul Cave, Folk Village, museums. Transportation in comfortable tour bus. 2 traditional Korean dinners (Day 1 welcome dinner, Day 4 farewell dinner). Bottled water during tours. Travel tips and Jeju guidebook.',
      'exclude' => 'International/domestic flights to/from Jeju. Travel insurance (highly recommended). Lunch and dinner on Days 2-3-5. Personal expenses and shopping. Optional activities: submarine tour (₩50,000), horseback riding (₩40,000), spa treatments, water sports. Tips for guide and driver (recommended ₩10,000/day per person). Single room supplement (₩800,000 total). Visa fees if applicable. Any items not mentioned in inclusions.',
      'nearby_hotel' => 'Jeju Shilla Hotel (5-star luxury with ocean view, spa, and infinity pool), The Shore Hotel Jeju (modern 4-star with beach access), Paradise Hotel Jeju (family-friendly with water park), Marriott Jeju Resort (golf course and multiple restaurants), Lotte Hotel Jeju (downtown location with mountain view), Ramada Plaza Jeju (budget-friendly with great facilities)',
      'map_url' => 'https://www.google.com/maps/place/Jeju+Island,+South+Korea/@33.3846216,126.1583923,10z',
    ]);

    $jejuPhotos = [
      'destinations/jeju-featured.jpg',
      'destinations/jeju-photo-1.jpg',
      'destinations/jeju-photo-2.jpg',
      'destinations/jeju-photo-3.jpg',
      'destinations/jeju-photo-4.jpg',
    ];

    foreach ($jejuPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $jeju->id,
        'photo' => $photo,
      ]);
    }

    $seoul = Destination::create([
      'title' => 'Seoul Metropolitan Experience - 5D4N Culture & K-Pop',
      'slug' => 'seoul-city-lights-culture',
      'description' => 'Dive deep into the heart of South Korea\'s dynamic capital city with this comprehensive 5-day Seoul adventure. Experience the perfect fusion of ancient traditions and cutting-edge modernity as you explore magnificent palaces from the Joseon Dynasty, wander through charming hanok villages, shop in world-class malls, and immerse yourself in the global K-pop phenomenon. Visit the heavily fortified DMZ border, taste authentic Korean street food, witness stunning city views from N Seoul Tower, and experience Seoul\'s legendary nightlife in trendy Hongdae and Gangnam districts. This tour is perfect for culture enthusiasts, K-pop fans, foodies, and anyone wanting to experience the vibrant energy of one of Asia\'s most exciting cities.',
      'country' => 'South Korea',
      'city' => 'Seoul',
      'price' => 7200000,
      'date_started' => '2025-11-25',
      'date_ended' => '2025-11-29',
      'type' => 'Cultural & Shopping',
      'view_count' => 320,
      'featured_photo' => 'destinations/seoul-featured.jpg',
      'min_people' => 2,
      'max_people' => 20,
    ]);

    DestinationDetail::create([
      'destination_id' => $seoul->id,
      'itinerary' => json_encode([
        'Day 1 - Arrival & Shopping Paradise' => 'Arrive at Incheon International Airport at 2:00 PM. Our guide will transfer you to your 4-star hotel in downtown Seoul (1-hour drive). After check-in and refreshment, head to Myeongdong Shopping Street, Seoul\'s premier shopping district filled with Korean cosmetics brands, fashion boutiques, and street food stalls. Try famous Korean snacks like hotteok (sweet pancakes), tteokbokki (spicy rice cakes), and twisted potatoes. Evening ascent to N Seoul Tower via cable car for breathtaking 360-degree panoramic views of Seoul\'s glittering skyline. Lock your love padlock at the tower\'s famous fence. Return to hotel around 9:00 PM. Welcome dinner featuring Korean BBQ (galbi and samgyeopsal) with unlimited side dishes.',
        
        'Day 2 - Royal Heritage & Traditional Culture' => 'Start your day at majestic Gyeongbokgung Palace (9:00 AM), the largest of Five Grand Palaces built in 1395. Witness the colorful Royal Guard Changing Ceremony (10:00 AM & 2:00 PM). Visit the National Folk Museum inside palace grounds. Walk through picturesque Bukchon Hanok Village, featuring 900 traditional Korean houses (hanok) on hills with stunning architecture. Photo opportunities at every corner! Optional hanbok rental available (₩20,000 for 4 hours) - get palace entry for free when wearing hanbok. Explore Insadong Street, the cultural heart of Seoul, browse antique shops, art galleries, traditional tea houses, and craft stores. Try traditional Korean tea ceremony. Watch street performers and buy unique souvenirs. Evening free for personal exploration or optional Nanta Show (cooking-themed non-verbal performance, additional ₩60,000).',
        
        'Day 3 - DMZ Historic Tour' => 'Early departure (7:30 AM) for full-day DMZ (Demilitarized Zone) tour to the border between North and South Korea. Visit Imjingak Park with Freedom Bridge. Enter the 3rd Infiltration Tunnel discovered in 1978 - walk through the tunnel dug by North Korea. View North Korea from Dora Observatory using high-powered telescopes. Visit Dorasan Station, the northernmost train station in South Korea, built for future Korean reunification. Lunch included at local restaurant. Stop at War Memorial of Korea Museum in Seoul displaying extensive military history. Return to hotel around 6:00 PM. Evening free time - suggestions: Namdaemun Market (traditional market), Dongdaemun Design Plaza (futuristic architecture), or Cheonggyecheon Stream night walk.',
        
        'Day 4 - Gangnam Style & K-Pop Culture' => 'Welcome to Gangnam, Seoul\'s most affluent district made globally famous by PSY\'s "Gangnam Style"! Visit COEX Mall, Asia\'s largest underground shopping mall with over 260 stores, Starfield Library (Instagram-worthy book towers), and Aquarium. Walk K-Star Road featuring bear sculptures painted by K-pop idols and entertainment company buildings (SM, JYP, etc.). Visit SM Town Museum for K-pop fans. Afternoon shopping at Garosugil, trendy tree-lined street with designer boutiques and cafes. Explore Hongdae area, youthful neighborhood near universities famous for indie music, street performances, cute cafes, and vibrant nightlife. Free time for club hopping or live music venues. Farewell dinner at traditional Korean restaurant with makgeolli (rice wine) tasting. Return to hotel late evening.',
        
        'Day 5 - Free Time & Departure' => 'Free morning for last-minute shopping or relaxation. Recommendations: visit Gyeongdong Market (herbal medicine market), Ihwa Mural Village (colorful street art), Gwangjang Market (traditional food market for bindaetteok and bibimbap), or relax at Korean spa (jjimjilbang experience). Check-out at 11:00 AM. Transfer to Incheon International Airport for 12:00 PM departure (arrive 2-3 hours before flight). Safe journey home with unforgettable Seoul memories!',
      ]),
      'arrival' => 'Pick-up service at Incheon International Airport (ICN) Terminal 1 or 2, Arrival Hall at 2:00 PM. Guide will hold "ACP Tours - Seoul" sign with passenger names. Please provide flight number and arrival time 48 hours in advance. Late arrival accepted with additional charges. Airport limousine bus option available if preferred. Contact: +82-2-XXX-XXXX (24/7)',
      'departure' => 'Hotel check-out at 11:00 AM on Day 5. Transfer to Incheon International Airport for 12:00 PM drop-off. Recommended flight departure: 3:00 PM or later for international flights (3-hour before requirement), 2:00 PM for domestic flights. Early check-out available upon request. Express airport train (AREX) tickets can be arranged.',
      'tnc' => 'BOOKING: Minimum 2 people required. PAYMENT: 30% deposit upon booking, 70% balance 21 days before departure. CANCELLATION: 30+ days: 80% refund. 21-29 days: 50% refund. 14-20 days: 30% refund. 7-13 days: 20% refund. Less than 7 days: No refund. SPECIAL REQUIREMENTS: DMZ tour requires passport (original, not copy). Children under 5 not permitted in DMZ tunnel. Photography restrictions apply at military sites. SEASONAL: Cherry blossom season (April) and autumn foliage (October-November) have peak prices, book early. FORCE MAJEURE: Full refund if tour cancelled due to government alerts, political situations, natural disasters. ITINERARY: Subject to change based on weather, traffic, or circumstances beyond control. All major attractions will be covered.',
      'include' => '4 nights accommodation at 4-star hotel Seoul downtown (Myeongdong/City Hall area, twin sharing). Daily breakfast buffet (American & Korean options). Airport transfers in air-conditioned vehicle (arrival & departure). Professional English-speaking tour guide full-time Days 1-4. Transportation: comfortable tour bus with WiFi. DMZ full-day tour including 3rd Tunnel, Dora Observatory, Imjingak Park. Entrance fees: Gyeongbokgung Palace, N Seoul Tower Observatory, War Memorial Museum. Cable car to N Seoul Tower. 2 group dinners (Day 1 Korean BBQ, Day 4 traditional Korean). Drinking water during tours. Seoul city map and guidebook. Free T-money card (₩10,000 credit) for subway/bus.',
      'exclude' => 'International/domestic flights to/from Seoul. Travel/medical insurance (mandatory recommendation). Korea visa fees if applicable. Lunch and dinner except specified (Days 1 & 4). Personal expenses, shopping, souvenirs. Optional activities: Hanbok rental ₩20,000, Nanta Show ₩60,000, K-pop concert tickets, cooking class, spa/sauna, additional museum entries. Tips for guide and driver (recommended ₩50,000 total per person). Single room supplement ₩1,200,000 total. Late-night taxi fares. Excess baggage fees. Any items not mentioned in inclusions. SIM card or portable WiFi rental.',
      'nearby_hotel' => 'Lotte Hotel Seoul (5-star luxury with executive lounge, city center), Shilla Stay Myeongdong (4-star modern, walking to shopping), Prince Hotel Seoul (mid-range with palace view), Novotel Ambassador Gangnam (business district location), Glad Hotel Yeouido (Han River view), Tmark Grand Hotel Myeongdong (family suites available), Ibis Styles Ambassador Seoul Myeongdong (budget-friendly), Westin Chosun Seoul (heritage property near palace)',
      'map_url' => 'https://www.google.com/maps/place/Seoul,+South+Korea/@37.5665,126.9780,11z',
    ]);

    $seoulPhotos = [
      'destinations/seoul-photo-1.jpg',
      'destinations/seoul-photo-2.jpg',
      'destinations/seoul-photo-3.jpg',
      'destinations/seoul-photo-4.jpg',
      'destinations/seoul-photo-5.jpg',
    ];

    foreach ($seoulPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $seoul->id,
        'photo' => $photo,
      ]);
    }

    $busan = Destination::create([
      'title' => 'Busan Coastal Paradise - 5D4N Beach & Temple',
      'slug' => 'busan-beach-temple-getaway',
      'description' => 'Discover South Korea\'s vibrant second-largest city and premier seaside destination on this 5-day coastal adventure. Busan perfectly blends natural beauty with urban sophistication - from pristine beaches and dramatic cliff temples to bustling fish markets and colorful hillside villages. Relax on famous Haeundae Beach, explore the sacred Haedong Yonggungsa Temple perched on ocean cliffs, wander through the charming Gamcheon Culture Village with its rainbow-colored houses, savor the freshest seafood at Jagalchi Fish Market, and experience Korea\'s largest traditional market. Walk on thrilling glass skywalks over the ocean, visit peaceful mountain temples, and enjoy spectacular sunrises over the East Sea. This tour is ideal for beach lovers, photographers, culture seekers, seafood enthusiasts, and anyone wanting to experience Korea beyond Seoul.',
      'country' => 'South Korea',
      'city' => 'Busan',
      'price' => 6800000,
      'date_started' => '2026-01-10',
      'date_ended' => '2026-01-14',
      'type' => 'Beach & Culture',
      'view_count' => 180,
      'featured_photo' => 'destinations/busan-featured.jpg',
      'min_people' => 2,
      'max_people' => 12,
    ]);

    DestinationDetail::create([
      'destination_id' => $busan->id,
      'itinerary' => json_encode([
        'Day 1 - Arrival & Beachfront Welcome' => 'Land at Gimhae International Airport at 11:00 AM where our guide welcomes you with a smile. Comfortable transfer to 4-star beachfront hotel at Haeundae, Busan\'s most prestigious beach area (30-minute scenic drive). Check-in and refresh before heading straight to the golden sands of Haeundae Beach - Korea\'s most famous 1.5km stretch of pristine coastline. Dip your toes in the East Sea, take selfies, and soak up the beach vibes. Walk along the coastal path to Dongbaek Island (Camellia Island), a small island connected to the mainland by scenic walking trails through pine forests. Visit the iconic APEC House (Nurimaru) perched on cliffs - the futuristic building hosted the 2005 APEC Summit. Enjoy panoramic ocean views and dramatic rock formations. Watch the waves crash against the cliffs as the sun begins to set. Welcome dinner at seaside seafood restaurant featuring Busan\'s specialty raw fish (hoe) and grilled shellfish. Try local soju cocktails. Evening stroll along the beach promenade. Return to hotel around 9:00 PM.',
        
        'Day 2 - Sacred Temples & Colorful Villages' => 'Early morning departure (8:00 AM) to witness sunrise prayers at Haedong Yonggungsa Temple, one of Korea\'s most spectacular Buddhist temples dramatically positioned on ocean cliffs with waves crashing below. Unlike most Korean temples found in mountains, this unique seaside temple offers breathtaking coastal views. Descend 108 stone steps to the temple grounds featuring ornate pagodas, a giant golden Buddha statue facing the sea, and twelve zodiac guardian statues. Light incense, make a wish (legend says prayers here always come true!), and explore the temple\'s beautiful architecture. Take countless Instagram-worthy photos with the ocean as your backdrop. Mid-morning drive to Gamcheon Culture Village (11:00 AM), nicknamed "Santorini of Korea" and "Machu Picchu of Busan" - a hillside labyrinth of colorful houses transformed into an artistic wonderland. Explore narrow alleyways filled with vibrant murals, quirky sculptures (including the famous Little Prince and Desert Fox statue), artisan cafes, and galleries. Get lost in this maze of creativity with each turn revealing new photo opportunities. Lunch at local restaurant. Afternoon visit to Jagalchi Fish Market, Korea\'s largest seafood market where ajumma (market ladies) sell every imaginable sea creature - live octopus, sea squirts, king crabs, abalone, and fish of every kind. Experience the energy, smells, and sights of authentic Korean market life. Dinner on your own (guide provides recommendations). Optional evening visit to Gwangalli Beach to see the spectacular Diamond Bridge (Gwangan Bridge) illuminated with LED lights reflecting on the water.',
        
        'Day 3 - Coastal Wonders & Thrilling Skywalks' => 'Full-day coastal exploration starting with Taejongdae Resort Park (9:00 AM), a natural paradise on Yeongdo Island featuring dramatic 200-meter-high coastal cliffs, pine forests, and a historic lighthouse dating back to 1906. Take the Danubi Train shuttle around the park for scenic views (₩3,000, saves energy for exploring). Walk to the observatory platform for stunning views of Tsushima Island (Japan) on clear days. Visit the ancient lighthouse and rocky coastline where waves create mesmerizing patterns. Legends say making a wish while throwing a coin into the ocean here brings good fortune. Continue to thrilling Oryukdo Skywalk, a U-shaped glass bridge extending over the ocean 35 meters above sea level. Walk on transparent glass floors with waves crashing directly below your feet - not for the faint-hearted! See the five (sometimes six) rocky islands of Oryukdo depending on the tide. Lunch at local seafood restaurant. Afternoon visit to peaceful Beomeosa Temple nestled in mountain forests, one of Korea\'s most important temples founded in 678 AD. Experience traditional Buddhist culture, see beautiful architecture, and enjoy the serene mountain atmosphere away from the city. Evening at trendy Seomyeon district, Busan\'s commercial heart perfect for shopping, dining, and nightlife. Free time to explore streets filled with restaurants, bars, cafes, and shops. Farewell dinner at authentic Korean BBQ restaurant featuring Busan-style galbi (marinated ribs).',
        
        'Day 4 - Street Food & Modern Busan' => 'Morning street food tour starting at BIFF Square (Busan International Film Festival Square), famous for its ssiat hotteok (seed-filled sweet Korean pancakes) - a must-try Busan specialty. Explore nearby Gukje Market and Bupyeong Kkangtong Market, Korea\'s largest traditional markets with over 10,000 stalls selling everything from clothes and textiles to Korean red ginseng and street snacks. Taste various Korean street foods: tteokbokki (spicy rice cakes), odeng (fish cake skewers), gimbap (Korean sushi rolls), bindaetteok (mung bean pancakes), and hotteok. Shop for souvenirs, Korean cosmetics, and unique items. Visit Yongdusan Park and climb Busan Tower (118 meters) for 360-degree city and harbor views. The park\'s name means "Dragon Head Mountain." Afternoon option to visit Shinsegae Centum City, certified by Guinness World Records as the world\'s largest department store, or relax at Haeundae Beach. Evening free for personal exploration. Consider night cruise on Busan Harbor, visit trendy cafes in Marine City\'s skyscrapers, or experience Korean spa culture at a jjimjilbang (24-hour bathhouse with saunas).',
        
        'Day 5 - Sunrise & Farewell' => 'Optional early wake-up (5:30 AM) for spectacular sunrise viewing at Gwangalli Beach - watch the sky change colors over the East Sea with Diamond Bridge in view. Famous among photographers and romantic couples. Return to hotel for breakfast and packing. Free morning for last-minute activities depending on interests and flight time. Suggestions: walk Songdo Beach Skywalk (another glass-floor coastal walkway), visit Seokbulsa Temple (unique temple carved into rock face on Geumjeongsan Mountain), explore Millak Raw Fish Town for final seafood feast, or relax at hotel spa/pool. Check-out at 12:00 PM. Transfer to Gimhae International Airport for 5:00 PM drop-off (arrive 2-3 hours before international flight). Safe journey home with unforgettable Busan memories, hundreds of photos, and maybe some extra kilos from amazing food!',
      ]),
      'arrival' => 'Pick-up service at Gimhae International Airport (PUS) at 11:00 AM, Domestic Arrival Hall Gate 1 or International Arrival Hall Gate 4. Guide will hold "ACP Tours - Busan" sign with passenger names. Please provide flight number, airline, and arrival time 48 hours before tour. Late/early arrival arrangements possible (additional charges). KTX train option from Seoul available. Emergency contact: +82-51-XXX-XXXX (24/7 Korean & English)',
      'departure' => 'Hotel check-out 12:00 PM on Day 5. Transfer to Gimhae International Airport for 5:00 PM drop-off. Recommended flight departure: 8:00 PM or later for international flights (arrive 3 hours before), 7:00 PM for domestic flights (arrive 2 hours before). Early check-out available upon request with luggage storage. Express train to Seoul (KTX) can be arranged.',
      'tnc' => 'BOOKING & PAYMENT: Minimum 2 people required to operate tour. 30% deposit due at booking confirmation, remaining 70% balance payment 14 days before departure date. CANCELLATION POLICY: 10+ days before tour: 80% refund (less processing fee). 5-9 days: 50% refund. 3-4 days: 30% refund. Less than 3 days or no-show: No refund. WEATHER CONDITIONS: Tours operate rain or shine. Beach activities may be modified due to sea conditions or typhoon warnings. Temple visits require modest clothing (shoulders and knees covered) - shawls and sarongs provided if needed. Skywalk closures due to strong winds are beyond our control. FORCE MAJEURE: Full refund if tour cancelled due to typhoons, government travel warnings, natural disasters, or circumstances beyond control. PEAK SEASON: Summer beach season (July-August) and autumn (September-October) have 20% price increase and require early booking. ITINERARY: Order and timing may adjust based on weather, traffic, temple events, or operational reasons. All major attractions will be included.',
      'include' => '4 nights accommodation at 4-star beachfront hotel Haeundae area (ocean or city view room, twin/double sharing). Daily buffet breakfast (Korean and Western options, vegetarian available). Round-trip airport transfers in comfortable air-conditioned vehicle. Professional English-speaking tour guide Days 1-4 (full-time). Transportation: modern tour bus with WiFi throughout tour. All entrance fees: Haedong Yonggungsa Temple, Taejongdae Danubi Train, Oryukdo Skywalk, Beomeosa Temple, Busan Tower. 2 group dinners (Day 1 seafood dinner, Day 3 Korean BBQ farewell dinner). Bottled drinking water during tours. Busan city map and attraction guidebook. Free Cashbee transportation card with ₩10,000 credit for buses/subway.',
      'exclude' => 'International/domestic flights to/from Busan. Travel and medical insurance (mandatory recommendation). Korea visa fees if applicable. Lunch daily (estimate ₩12,000-20,000 per meal, guide assists with ordering). Dinner on Days 2 and 4 (own arrangement, recommendations provided). Personal expenses, shopping, souvenirs. Optional activities: seafood meal at Jagalchi Market upper floor restaurants, night harbor cruise ₩30,000, temple stay program, spa/sauna/jjimjilbang entry, water sports/parasailing at beach, sunrise photo tour, cooking class. Tips for guide and driver (recommended ₩50,000 total per person for 5 days). Single room supplement ₩1,200,000 total. Late check-out fees. SIM card or portable WiFi device rental ₩5,000/day. Excess baggage charges. Any items not mentioned in inclusions list.',
      'nearby_hotel' => 'Paradise Hotel Busan (5-star luxury with casino, spa, multiple restaurants, direct beach access), Westin Chosun Busan (premium oceanfront with executive lounge), Haeundae Grand Hotel (family-friendly with outdoor pool and kids club), Park Hyatt Busan (contemporary luxury in Marine City towers), Lotte Hotel Busan (business hotel near Seomyeon shopping), Novotel Ambassador Busan (mid-range with harbor views), Ibis Ambassador Busan City Centre (budget-friendly central location), Ananti Hilton Busan (resort-style with infinity pool)',
      'map_url' => 'https://www.google.com/maps/place/Busan,+South+Korea/@35.1796,129.0756,11z',
    ]);

    $busanPhotos = [
      'destinations/busan-photo-1.jpg',
      'destinations/busan-photo-2.jpg',
      'destinations/busan-photo-3.jpg',
    ];

    foreach ($busanPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $busan->id,
        'photo' => $photo,
      ]);
    }

    $gyeongju = Destination::create([
      'title' => 'Gyeongju Ancient Capital - 4D3N UNESCO Heritage',
      'slug' => 'gyeongju-historical-heritage',
      'description' => 'Journey into Korea\'s glorious past with this immersive 4-day exploration of Gyeongju, the ancient capital of the Silla Kingdom (57 BC - 935 AD) and proudly known as "the museum without walls." This UNESCO World Heritage city contains more tombs, temples, rock carvings, pagodas, and archaeological sites than any other place in South Korea. Walk among grass-covered royal burial mounds at Daereungwon Tomb Complex, marvel at the architectural masterpiece of Bulguksa Temple, discover the serene beauty of Seokguram Grotto with its stunning stone Buddha, observe stars from Asia\'s oldest astronomical observatory, witness magical night reflections at Anapji Pond, and experience traditional Korean life at a 500-year-old folk village. This tour is perfect for history buffs, culture enthusiasts, photographers, and anyone fascinated by ancient civilizations and Korean heritage.',
      'country' => 'South Korea',
      'city' => 'Gyeongju',
      'price' => 5500000,
      'date_started' => '2026-02-15',
      'date_ended' => '2026-02-18',
      'type' => 'Historical & Cultural',
      'view_count' => 145,
      'featured_photo' => 'destinations/gyeongju-featured.jpg',
      'min_people' => 4,
      'max_people' => 18,
    ]);

    DestinationDetail::create([
      'destination_id' => $gyeongju->id,
      'itinerary' => json_encode([
        'Day 1 - Sacred Sites & Mountain Buddha' => 'Arrive at Gyeongju KTX Station (high-speed train from Seoul/Busan) at 1:00 PM where guide meets you. Transfer to traditional hanok accommodation in the city center (20 minutes). Check-in to beautifully preserved Korean traditional house with ondol (underfloor heating). Lunch at local restaurant featuring Gyeongju specialties: ssambap (rice with leafy wraps) and hwangnam bread (red bean pastry). Begin spiritual journey at Bulguksa Temple (2:00 PM), a UNESCO World Heritage masterpiece and one of Korea\'s most important Buddhist temples built in 751 AD. Admire elaborate wooden architecture, stone bridges (Cheongungyo and Baekungyo representing journey from earth to enlightenment), Dabotap and Seokgatap stone pagodas (depicted on 10 won coin), and beautifully landscaped gardens. Continue uphill to Seokguram Grotto (3:30 PM), an artificial stone temple on mountain slopes housing a magnificent 3.5-meter granite Buddha statue facing the East Sea - considered a masterpiece of Buddhist art and science. Experience the serene spiritual atmosphere. Return to Gyeongju city for welcome dinner at traditional Korean restaurant. Evening walk around downtown area. Rest at hanok accommodation.',
        
        'Day 2 - Royal Legacy & Celestial Wonder' => 'Morning visit (9:00 AM) to Daereungwon Tomb Complex (Tumuli Park), an extraordinary archaeological park containing 23 large ancient Silla royal burial mounds covered in grass, resembling green hills. Enter Cheonmachong (Heavenly Horse Tomb) - the only tomb open to public - to see replicated treasures and understand Silla burial customs. Walk among the massive tombs in peaceful park atmosphere - surreal and photogenic. Continue to Cheomseongdae Observatory, Asia\'s oldest existing astronomical observatory built in 632 AD, a 9-meter stone tower that helped Silla astronomers track stars. Learn about ancient Korean scientific achievements. Visit nearby Gyerim Forest, mythical birthplace of Kim clan. Lunch at Gyeongju Hanjeongsik restaurant (traditional full-course Korean meal with 12+ side dishes). Afternoon visit to Gyeongju National Museum to see invaluable Silla artifacts including the Divine Bell of King Seongdeok (largest bell in Korea), gold crowns, pottery, and Buddhist art. Free time for shopping at traditional craft stores. Evening at Donggung Palace and Wolji Pond (formerly Anapji Pond), a stunning palace complex built in 674 AD. As darkness falls, palace buildings and surrounding trees reflect perfectly in the pond\'s still water creating magical mirror images - one of Korea\'s most photographed scenes. Dinner on own with guide recommendations.',
        
        'Day 3 - Living History & Mountain Serenity' => 'Depart (8:30 AM) for Yangdong Folk Village, a UNESCO World Heritage site and Korea\'s largest traditional village preserving 500+ years of Joseon Dynasty clan culture. Walk through authentic hanok houses still inhabited by descendants of the Yangban (aristocratic) families. See thatched-roof commoner houses, tile-roof noble residences, Confucian academies, and beautiful natural setting surrounded by mountains. Understand traditional Korean class structure and lifestyle. Meet village elders and learn about Korean ancestral rituals. Participate in traditional tea ceremony at village tea house - taste Korean green tea and traditional rice cakes while learning tea etiquette. Lunch at village restaurant featuring farm-to-table Korean cuisine. Afternoon drive through scenic countryside to Girimsa Temple (founded 643 AD), a peaceful mountain temple off the typical tourist path. Experience authentic temple atmosphere away from crowds. Walk forest trails, see ancient stone pagodas, and feel the spiritual tranquility of mountain Buddhism. Visit temple museum with ancient artifacts. Return to Gyeongju for farewell dinner featuring Gyeongju Gyodong Ssambap (special rice wrapped in various leaves with 30+ side dishes) - declared UNESCO Intangible Cultural Heritage.',
        
        'Day 4 - Cultural Treasures & Farewell' => 'Final morning free time for personal exploration based on interests. Options: Visit Oreung (Five Royal Tombs) for peaceful morning walk, explore Gyeongju Historic Areas on bicycle (rental available), shop for Gyeongju crafts (traditional pottery, Silla jewelry replicas, hwangnam bread as gifts), relax at traditional Korean spa, or revisit favorite sites for better photos. Late check-out at 12:00 PM from hanok. Quick visit to Gyeongju Gyochon Traditional Village near downtown - small hanok village with Choi clan house, traditional craft workshops, and photo opportunities. Lunch at local restaurant. Transfer to Gyeongju Station for 4:00 PM departure via KTX train. Return home with deep appreciation for Korean history and unforgettable memories of ancient Silla Kingdom!',
      ]),
      'arrival' => 'Pick-up at Gyeongju Station (KTX high-speed train terminal) at 1:00 PM on Day 1. Guide will wait at main exit with "ACP Tours - Gyeongju" sign. Please book KTX train from Seoul Station (2 hours) or Busan Station (30 minutes) arriving at 1:00 PM. Train tickets not included. Provide arrival train number 2 days before tour. Alternative: Gyeongju Express Bus Terminal pickup available. Emergency contact: +82-54-XXX-XXXX',
      'departure' => 'Transfer to Gyeongju Station at 3:30 PM on Day 4 for 4:00 PM or later KTX train departure. Recommend booking 5:00 PM or 6:00 PM train for buffer time. Alternative drop-off at Express Bus Terminal for bus to Seoul/Busan. Luggage storage available at station. Private taxi to Busan/Ulsan can be arranged (additional cost).',
      'tnc' => 'BOOKING & PAYMENT: Minimum 4 people required (private tour available for 2-3 with 40% surcharge). 30% deposit at booking, full payment 10 days before departure. CANCELLATION: 10+ days: 70% refund. 5-9 days: 50% refund. 2-4 days: 20% refund. Less than 2 days: No refund. ACCOMMODATION: Traditional hanok stay with shared bathroom facilities (ondol floor sleeping on futon). Modern hotel upgrade available (+₩400,000 per person). PHYSICAL REQUIREMENTS: Moderate walking required. Comfortable shoes essential. Temple visits have stairs. Not wheelchair accessible. DRESS CODE: Modest clothing for temples (shoulders/knees covered). Hanbok rental available for photos (₩15,000). WEATHER: Spring (April-May) cherry blossoms and autumn (October-November) foliage are peak seasons - book early. Winter can be cold. SPECIAL: Historian guide provides in-depth historical context - bring curiosity! Photography allowed at most sites (flash prohibited in museums). MEALS: Traditional Korean meals - vegetarian options available with advance notice.',
      'include' => '3 nights traditional hanok accommodation in Gyeongju (twin/family room sharing, ondol floor sleeping). Daily breakfast (Korean-style with rice, soup, side dishes). All meals included: 3 lunches, 3 dinners (Day 1 welcome dinner, Day 3 farewell dinner, plus Day 2 dinner). Round-trip transfers between Gyeongju Station and accommodation. Professional English-speaking historian tour guide all 4 days. Transportation: comfortable air-conditioned vehicle throughout tour. UNESCO site entrance fees: Bulguksa Temple, Seokguram Grotto, Daereungwon Tomb Complex, Yangdong Folk Village. Museum entries: Gyeongju National Museum, Cheonmachong Tomb interior. Donggung Palace & Wolji Pond entry including night view. Girimsa Temple entrance. Traditional tea ceremony experience at Yangdong Village. Gyeongju guidebook and historical context materials. Bottled water during tours.',
      'exclude' => 'KTX train tickets to/from Gyeongju (Seoul-Gyeongju ₩60,000-80,000 roundtrip, Busan-Gyeongju ₩20,000 roundtrip - book via www.letskorail.com). Travel and medical insurance. Personal expenses, shopping, souvenirs. Optional activities: Bicycle rental ₩15,000/day, hanbok rental for photos ₩15,000, additional temple visits, cooking class ₩80,000, traditional paper-making workshop. Modern hotel upgrade ₩400,000 per person. Private tour supplement for 2-3 people (40% additional). Tips for guide and driver (suggest ₩40,000 per person total). Single room supplement ₩600,000 total. Late-night snacks or drinks. Laundry service. Any items not mentioned in inclusions.',
      'nearby_hotel' => 'Gyeongju Hilton (5-star with golf course and spa), Commodore Hotel Gyeongju (lakeside resort with theme park nearby), Kolon Hotel Gyeongju (business hotel central location), Gyeongju GGU Hotel (modern boutique), Lahan Select Gyeongju (mid-range with traditional elements), Gyeongju Hyundai Hotel (family-friendly near attractions), Benikea Gyeongju Chosun (budget-friendly), Traditional Hanok Guesthouses in Gyeongju Gyochon Village',
      'map_url' => 'https://www.google.com/maps/place/Gyeongju,+South+Korea/@35.8562,129.2247,12z',
    ]);

    $gyeongjuPhotos = [
      'destinations/gyeongju-photo-1.jpg',
      'destinations/gyeongju-photo-2.jpg',
      'destinations/gyeongju-photo-3.jpg',
      'destinations/gyeongju-photo-4.jpg',
    ];

    foreach ($gyeongjuPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $gyeongju->id,
        'photo' => $photo,
      ]);
    }

    $incheon = Destination::create([
      'title' => 'Incheon Gateway Explorer - 3D2N Port & Future City',
      'slug' => 'incheon-port-island-adventure',
      'description' => 'Discover the fascinating contrasts of Incheon, Korea\'s third-largest city and home to the nation\'s main international gateway. This 3-day adventure showcases Incheon\'s unique identity - from Korea\'s only official Chinatown with colorful architecture and authentic Chinese-Korean fusion cuisine, to the ultra-modern smart city of Songdo with futuristic skyscrapers and canal parks. Explore historical sites dating back to Korea\'s opening to the West, relax on island beaches, witness the massive tidal flats of the Yellow Sea, enjoy fresh seafood at traditional markets, and experience cutting-edge urban planning. Perfect for travelers with layovers, those seeking alternatives to Seoul, families, and anyone interested in port city culture and modern Korean development.',
      'country' => 'South Korea',
      'city' => 'Incheon',
      'price' => 4200000,
      'date_started' => '2026-03-05',
      'date_ended' => '2026-03-07',
      'type' => 'City & Island',
      'view_count' => 95,
      'featured_photo' => 'destinations/incheon-featured.jpg',
      'min_people' => 2,
      'max_people' => 10,
    ]);

    DestinationDetail::create([
      'destination_id' => $incheon->id,
      'itinerary' => json_encode([
        'Day 1 - Historic Port & Chinatown Culture' => 'Meet at Incheon International Airport at 10:00 AM (perfect for layover travelers or red-eye arrivals). Transfer to downtown Incheon (40 minutes via airport railroad). Check-in at 4-star hotel near Chinatown. Begin exploration at Incheon Chinatown, Korea\'s only official Chinatown established in 1884 when Incheon opened as an international port. Walk streets lined with colorful Chinese-style gates (paifang), red lanterns, and unique architecture blending Chinese and Korean influences. Visit Jjajangmyeon Museum dedicated to Korea\'s beloved Chinese-Korean black bean noodle dish invented here in 1905. Lunch at famous jjajangmyeon restaurant - taste the legendary dish where it originated! Explore Fairytale Village with whimsical murals and sculptures. Walk to adjacent Jayu Park (Freedom Park), Korea\'s first Western-style park established 1888, located on hilltop with panoramic views of Incheon Port and Yellow Sea. See the statue of General MacArthur commemorating Incheon Landing during Korean War. Visit nearby Open Port Area to see preserved buildings from Japanese colonial period, old banks, and warehouses converted to cultural spaces. Evening at Sinpo International Market, bustling traditional market famous for dakgangjeong (sweet crispy fried chicken) invented here - sample from multiple stalls! Try various Korean street foods and buy souvenirs. Welcome dinner at Chinese-Korean restaurant featuring tangsuyuk (sweet and sour pork). Return to hotel.',
        
        'Day 2 - Island Beaches & Natural Wonders' => 'Morning departure (9:00 AM) to Yeongjong Island where the airport is located. Visit Eurwangni Beach, a beautiful 700-meter sandy beach facing west toward China across Yellow Sea. Depending on tide schedule, witness or learn about impressive tidal flats (up to 2km of exposed seabed during low tide) - one of world\'s most dramatic tidal ranges. Walk along beach promenade, breathe fresh sea air, collect shells. Visit nearby cafes for ocean views. Drive to Wangsan Beach and Yongyudo Island (connected by bridge) for more coastal scenery and fresh seafood. Lunch at seafood restaurant featuring grilled fish, seafood pancakes, and clam soup. Afternoon visit to Incheon Grand Park, massive 727-hectare park with botanical gardens, lakes, forests, and walking trails. Option to visit Incheon Children\'s Museum or Zoo if traveling with kids. Take cable car to mountain peak for city views. Alternatively visit Muui-do Island (ferry required, weather dependent) for quiet beach experience and cycling. Return to Incheon city center. Evening free time for shopping at Bupyeong Underground Shopping Mall or Lotte Department Store. Dinner on own - guide provides recommendations for Korean BBQ or hotpot.',
        
        'Day 3 - Future City & Departure' => 'Morning visit to Songdo International Business District, Korea\'s futuristic smart city built on reclaimed land featuring eco-friendly skyscrapers, sensor-based systems, and visionary urban planning. Walk through Songdo Central Park, inspired by New York\'s Central Park, featuring Korea\'s first seawater canal where you can take water taxi rides. See Tri-Bowl performing arts center with its distinctive three dome architecture. Visit NCube Canal Walk with modern shops and cafes along waterways. Photo opportunities at futuristic buildings and art installations. Experience what Korean cities of the future might look like! Option to visit nearby Compact Smart City Exhibition if interested in urban planning and technology. Browse Hyundai Premium Outlet Songdo for last-minute shopping at discount designer brands. Late check-out at 12:00 PM. Lunch at Songdo or airport. Transfer to Incheon International Airport for 6:00 PM check-in. If you have time before flight, explore the airport\'s many attractions: Korean Cultural Street, Traditional Performance Hall, free showers, relaxation areas, Gardens, Museums. Perfect end to your Incheon adventure!',
      ]),
      'arrival' => 'Meeting point at Incheon International Airport (ICN) Terminal 1 or 2, Arrival Hall at 10:00 AM. Guide will hold "ACP Tours - Incheon" sign at Meeting Point Zone (between Gates 4-5 Terminal 1, or Gate 5-6 Terminal 2). Ideal for travelers with layovers or early arrivals. Luggage storage available at airport if needed. Provide flight details 24 hours in advance. Alternative meeting at Incheon Station (Seoul Line 1 terminal) possible. Contact: +82-32-XXX-XXXX',
      'departure' => 'Check-out 12:00 PM Day 3. Transfer to Incheon International Airport for 6:00 PM arrival. Suitable for evening or night flights (recommend 9:00 PM or later departure for international flights). Early departure possible if flight schedule requires (breakfast box provided). Airport limousine bus to Seoul option available if continuing to Seoul (₩15,000, 70 minutes).',
      'tnc' => 'BOOKING: Minimum 2 people. Ideal for layover travelers (need 48+ hour layover). PAYMENT: 40% deposit at booking, 60% balance 7 days before tour. CANCELLATION: 7+ days: 80% refund. 3-6 days: 50% refund. Less than 3 days or within 48 hours: No refund. WEATHER: Island/beach activities subject to weather and tide schedules. Alternative indoor activities provided during bad weather. Ferry to Muui-do may cancel due to rough seas. FLEXIBILITY: Itinerary adaptable based on interests - more beaches, more shopping, more culture - discuss with guide. LUGGAGE: Large luggage can stay at hotel Day 2 while visiting islands (bring day bag). Airport luggage storage available (₩4,000-6,000 per day). TRANSIT: Perfect for travelers with long layovers wanting to explore beyond airport - must have valid Korean visa or visa-free entry eligibility. SPECIAL: Jjajangmyeon (black bean noodles) and dakgangjeong (crispy chicken) are Incheon specialties - vegetarian options limited.',
      'include' => '2 nights accommodation at 4-star hotel near Incheon Chinatown (twin sharing, city view). Daily breakfast buffet. Airport round-trip transfers (arrival Day 1, departure Day 3). Professional English-speaking tour guide Days 1-3. Transportation: comfortable vehicle throughout tour. Entrance fees: Jayu Park, Incheon Grand Park cable car, Songdo Central Park. Welcome dinner Day 1 (Chinese-Korean cuisine). Water taxi ride in Songdo Canal (weather permitting). Bottled drinking water during tours. Incheon map and guidebook. Cashbee transit card with ₩5,000 credit.',
      'exclude' => 'International flights. Korea visa if required. Travel and medical insurance. Lunch all days (estimate ₩12,000-18,000 per meal). Dinner Days 2-3 (own arrangement, guide assists). Ferry to Muui-do Island if chosen (₩8,000 roundtrip). Personal expenses, shopping, souvenirs. Optional: Incheon Children\'s Museum ₩5,000, Zoo entry ₩3,000, additional water taxi rides ₩5,000, bicycle rental, water sports. Tips for guide (suggest ₩30,000 per person total). Single room supplement ₩450,000 total. Early breakfast box if needed ₩15,000. Airport lounge access. SIM card rental.',
      'nearby_hotel' => 'Paradise City Hotel (5-star integrated resort with casino, spa, indoor beach, near airport), Grand Hyatt Incheon (luxury airport hotel), Orakai Songdo Park Hotel (modern hotel in Songdo smart city), Nest Hotel Incheon (4-star near Chinatown), Oakwood Premier Incheon (serviced residences), Hotel Soho (boutique budget option), Sea & Moon Pension (island accommodation on Eurwangni Beach)',
      'map_url' => 'https://www.google.com/maps/place/Incheon,+South+Korea/@37.4563,126.7052,11z',
    ]);

    $incheonPhotos = [
      'destinations/incheon-photo-1.jpg',
      'destinations/incheon-photo-2.jpg',
      'destinations/incheon-photo-3.jpg',
    ];

    foreach ($incheonPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $incheon->id,
        'photo' => $photo,
      ]);
    }

    $sokcho = Destination::create([
      'title' => 'Sokcho Mountain Paradise - 5D4N Seoraksan Hiking',
      'slug' => 'sokcho-nature-mountain-retreat',
      'description' => 'Embark on an unforgettable mountain adventure in Sokcho, gateway to magnificent Seoraksan National Park - one of Korea\'s most spectacular natural treasures and UNESCO Biosphere Reserve. This 5-day nature retreat combines challenging hiking trails through dramatic granite peaks, serene Buddhist temples nestled in mountain valleys, thrilling cable car rides to ancient fortresses, cascading waterfalls, soothing natural hot springs, and fresh seafood dining by the East Sea coast. Trek to Ulsanbawi Rock for breathtaking panoramic views, visit the giant bronze Buddha at Sinheungsa Temple, relax in healing hot spring waters, explore traditional fish markets, and wake up to mountain air and stunning sunrise views. Perfect for outdoor enthusiasts, nature photographers, hikers of moderate fitness levels, and anyone seeking rejuvenation away from urban life.',
      'country' => 'South Korea',
      'city' => 'Sokcho',
      'price' => 6200000,
      'date_started' => '2026-04-20',
      'date_ended' => '2026-04-24',
      'type' => 'Nature & Hiking',
      'view_count' => 165,
      'featured_photo' => 'destinations/sokcho-featured.jpg',
      'min_people' => 4,
      'max_people' => 15,
    ]);

    DestinationDetail::create([
      'destination_id' => $sokcho->id,
      'itinerary' => json_encode([
        'Day 1 - Arrival & Coastal Welcome' => 'Arrive at Sokcho Express Bus Terminal at 11:00 AM (3.5-hour bus from Seoul Dong Seoul Terminal). Guide welcomes you and transfers to comfortable mountain lodge accommodation near Seoraksan National Park entrance (15-minute drive). Check-in and unpack hiking gear. Afternoon coastal exploration starting with Sokcho Beach walk along the East Sea (also called Sea of Japan). Feel the sea breeze and see local fishermen at work. Visit bustling Daepo Port Fish Market, one of Korea\'s major fishing ports where fresh catches are sold daily - see live octopus, squid, crabs, and various fish species. Watch ajumma expertly prepare fresh seafood. Optional: buy fresh seafood and have it prepared at market restaurants (additional cost). Stroll through nearby Abai Village, North Korean refugee settlement with unique food culture - try Abai Sundae (blood sausage) and take hand-pulled ferry (₩500) across Cheongcho Lake. Welcome dinner at seafood restaurant featuring grilled mackerel, sashimi platter, and seafood pancakes. Evening briefing about hiking plans and safety. Early rest before mountain adventures.',
        
        'Day 2 - Seoraksan Main Valley & Temple' => 'Early breakfast at 7:00 AM. Depart for Seoraksan National Park main entrance (Outer Seorak) at 8:00 AM. Purchase park admission and begin mountain adventure! First stop: Sinheungsa Temple, one of Korea\'s most important Zen Buddhist temples founded in 652 AD. Walk through beautiful temple grounds and see the magnificent 14.6-meter bronze Great Unification Buddha statue - largest seated bronze Buddha in Korea overlooking the mountains. Light incense and feel the spiritual tranquility. Continue uphill through pine forests on well-maintained trails (moderate difficulty, 30-minute walk) to Gwongeumseong Fortress Cable Car station. Take thrilling cable car ride (8 minutes) up steep mountainside to ancient fortress ruins at 800 meters elevation. The cable car offers spectacular bird\'s-eye views of dramatic granite peaks, colorful rock formations, and endless valleys. At the top, hike remaining 10 minutes to fortress ruins for 360-degree panoramic views of Seoraksan\'s jagged peaks and East Sea coastline - absolutely breathtaking and worth every step! Packed lunch at mountain viewpoint. Descend via cable car. Afternoon option for moderate 2-hour hike to Biryong Falls (Flying Dragon Falls), beautiful 25-meter waterfall cascading through moss-covered rocks and forest. Return to lodge for rest. Dinner at lodge or nearby Korean restaurant. Evening free time - optional visit to local hot spring spa.',
        
        'Day 3 - Challenging Summit Hike' => 'Early wake-up at 5:30 AM for today\'s main challenge: Ulsanbawi Rock hike, one of Seoraksan\'s most iconic and rewarding trails. After breakfast, enter park at 7:00 AM (beat the crowds!). This moderately challenging hike covers 3.6km round trip with 888 metal stairway steps near the summit - requires good fitness but doable for most people with determination. Ascend through beautiful forests with mountain streams, passing rock formations and Buddhist hermitages clinging to cliffs. The infamous metal stairways are steep but offer incredible views with each step upward. Summit at 873 meters elevation for absolutely spectacular 360-degree panorama - see all of Seoraksan\'s granite peaks, East Sea coastline, and on clear days even North Korean mountains. Perfect photo moment! Descend carefully (harder on knees than ascending). Lunch at park restaurant. Afternoon relaxation at natural hot spring spa facility - soak tired muscles in mineral-rich waters surrounded by mountain views. Various indoor and outdoor pools, saunas, and relaxation areas. Spend 2-3 hours rejuvenating. Return to lodge for rest. Farewell dinner at Korean BBQ restaurant celebrating your hiking achievements. Share stories and photos with fellow hikers.',
        
        'Day 4 - Coastal Temples & Beach Leisure' => 'More relaxed day after yesterday\'s challenging hike. Breakfast at lodge. Depart (9:00 AM) for coastal drive south to beautiful Naksansa Temple, one of Korea\'s most scenic seaside temples founded in 671 AD. Perched on clifftops overlooking the East Sea, this temple offers unique combination of Buddhist spirituality and ocean views. See the seven-story stone pagoda, Hongyeonam hermitage on cliff edge, and white Haesugwaneumsang Bodhisattva statue facing the sea. Walk meditation paths through pine trees with ocean breeze and wave sounds - deeply peaceful atmosphere. Continue to nearby Naksan Beach, 4km stretch of white sand perfect for walking and relaxation. Free time to walk barefoot on beach, take photos, or relax at beachfront cafes. Lunch at seaside restaurant. Afternoon option: visit Seorak Waterpia indoor water park for fun slides and pools (additional cost), or explore Sokcho tourist fishing village, or shop for souvenirs in Sokcho central market. Evening special farewell dinner: fresh seafood BBQ (grilled whole fish, shellfish, shrimp) at beachfront restaurant watching sunset over East Sea. Return to lodge.',
        
        'Day 5 - Leisure & Departure' => 'Final breakfast at lodge with mountain views. Free morning based on departure time and interests. Recommendations: short morning hike on easy trails near lodge, revisit favorite spots in Seoraksan for better photos, relax at lodge facilities, visit Sokcho Expo Park, shop at Jungang Market for dried seafood and local specialties as gifts, or simply enjoy final moments in mountain air. Check-out at 11:00 AM. Transfer to Sokcho Express Bus Terminal for 3:00 PM or later bus to Seoul. Allow buffer time as mountain roads can be busy on weekends. Alternative: stay extra night in Sokcho to explore DMZ tours (available from Sokcho) or Goseong Unification Observatory. Return home with incredible memories, hundreds of photos, refreshed body and mind, and new appreciation for Korea\'s natural beauty!',
      ]),
      'arrival' => 'Pick-up at Sokcho Express Bus Terminal at 11:00 AM on Day 1. Guide will wait at main terminal exit with "ACP Tours - Sokcho" sign. Please book express bus from Seoul Dong Seoul Terminal (depart 7:30 AM, ₩22,000, 3.5 hours). Bus tickets not included - book at www.kobus.co.kr. Provide bus company and departure time 2 days before tour. Alternative: KTX train to Gangneung (2 hours) then local bus to Sokcho (1 hour). Emergency contact: +82-33-XXX-XXXX',
      'departure' => 'Check-out at 11:00 AM on Day 5. Transfer to Sokcho Express Bus Terminal for 3:00 PM or later bus to Seoul. Recommend booking 4:00 PM or 5:00 PM bus for comfortable timing. Bus journey 3.5-4 hours depending on traffic. Private taxi to Seoul/Gangneung can be arranged (additional cost ₩150,000). Alternative drop-off at Gangneung KTX Station for train to Seoul.',
      'tnc' => 'BOOKING & REQUIREMENTS: Minimum 4 people required. Moderate fitness level essential - able to climb 888 steps and hike 3-4 hours. Not suitable for people with severe knee problems, heart conditions, or mobility issues. Age 12-65 recommended for full hiking program. Children 8-11 possible with modified easier trails. PAYMENT: 30% deposit at booking, full payment 10 days before departure. CANCELLATION: 10+ days: 70% refund. 5-9 days: 40% refund. 2-4 days: 20% refund. Less than 2 days: No refund. WEATHER: Tours operate rain or shine (hiking more beautiful in light rain!). Heavy rain, snow, strong winds may close cable car or restrict trails - alternative activities provided. Autumn (September-November) brings spectacular fall foliage but crowded trails. Spring (April-May) offers cherry blossoms. HIKING GEAR: Proper hiking boots mandatory (no sneakers/sandals). Trekking poles recommended. Rain jacket essential. Layered clothing needed (mountain weather changes). Gear rental available at park (₩10,000/item). FORCE MAJEURE: Full refund if national park closes due to weather emergencies. MEALS: Korean mountain lodge food - hearty and nutritious. Vegetarian modifications available with 7-day advance notice.',
      'include' => '4 nights accommodation at comfortable mountain lodge near Seoraksan Park entrance (twin/triple room sharing, heated ondol rooms). Daily breakfast (Korean-style). 3 lunches (Day 2 packed lunch, Days 3-4 at restaurants). 4 dinners (Day 1 seafood, Day 2 Korean BBQ, Day 3 Korean meal, Day 4 seafood BBQ farewell). Round-trip transfers Sokcho Terminal and lodge. Professional English-speaking hiking guide Days 1-5 (experienced mountain guide with first-aid certification). Transportation: comfortable vehicle for park transfers and sightseeing. Seoraksan National Park entrance fees (4 days access). Gwongeumseong Fortress cable car tickets (roundtrip). Hot spring spa entry Day 3 (2-3 hours access). Sinheungsa Temple entry. Naksansa Temple entry. Bottled water during hikes. First-aid kit and emergency supplies. Seoraksan trail map and hiking guidebook. Hiking stick rental (if needed).',
      'exclude' => 'Express bus tickets to/from Sokcho (Seoul-Sokcho ₩22,000 each way, book at kobus.co.kr or terminal). Train tickets if using KTX option. Travel and medical insurance (mandatory for hiking activities). Personal hiking gear (boots, backpack, poles, rain jacket - rental available at park). Lunch Day 1 and Day 5. Optional seafood purchases at fish markets. Hot spring spa Day 2 evening (optional, ₩15,000). Seorak Waterpia water park entry (₩45,000). Cable car photos (professional photos at cable car, optional ₩10,000). Personal expenses, souvenirs, snacks. Tips for guide and driver (recommended ₩60,000 per person total). Single room supplement ₩900,000 total. Hiking gear rental at park (₩10,000 per item per day). Laundry services. Any items not mentioned in inclusions.',
      'nearby_hotel' => 'Kensington Stars Hotel Seorak (5-star mountain resort with spa), Seorak Plaza Hotel (4-star near park entrance), Seorak Pine Resort (mid-range with mountain view), Goodstay Seoraksan Hotel (budget-friendly), Hanwha Resort Seorak Sorano (family condos), Mt. Seorak Tourist Hotel (basic lodge-style), Goodstay Benikea Hotel Maremons (affordable option), Traditional Mountain Lodges and Minbak near park entrance',
      'map_url' => 'https://www.google.com/maps/place/Sokcho,+South+Korea/@38.2070,128.5918,13z',
    ]);

    $sokchoPhotos = [
      'destinations/sokcho-photo-1.jpg',
      'destinations/sokcho-photo-2.jpg',
      'destinations/sokcho-photo-3.jpg',
      'destinations/sokcho-photo-4.jpg',
    ];

    foreach ($sokchoPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $sokcho->id,
        'photo' => $photo,
      ]);
    }

    $daegu = Destination::create([
      'title' => 'Daegu Modern City Discovery - 4D3N Urban Culture',
      'slug' => 'daegu-urban-traditional-mix',
      'description' => 'Explore Daegu, Korea\'s dynamic fourth-largest city known as the "Apple City" for its surrounding orchards and hot summer climate. This 4-day urban adventure reveals Daegu\'s fascinating blend of Korean War history, traditional medicine culture, thriving arts scene, massive traditional markets, modern entertainment, and vibrant youth culture. Shop at Korea\'s oldest and largest traditional market, stroll streets dedicated to folk singer Kim Gwangseok, visit unique Oriental medicine museums and alleys, ascend mountains for panoramic city views, pray at hilltop Buddha statue for exam success, enjoy theme park thrills and tower views, and experience trendy cafe culture and legendary nightlife. Known for textile industry and as birthplace of "Chimaek" (chicken and beer) culture, Daegu offers authentic Korean urban experience away from tourist crowds. Perfect for culture enthusiasts, K-pop fans, foodies, shoppers, and travelers seeking Korea beyond Seoul.',
      'country' => 'South Korea',
      'city' => 'Daegu',
      'price' => 5800000,
      'date_started' => '2026-05-15',
      'date_ended' => '2026-05-18',
      'type' => 'Urban & Cultural',
      'view_count' => 110,
      'featured_photo' => 'destinations/daegu-featured.jpg',
      'min_people' => 2,
      'max_people' => 14,
    ]);

    DestinationDetail::create([
      'destination_id' => $daegu->id,
      'itinerary' => json_encode([
        'Day 1 - Markets & Street Culture' => 'Arrive at Daegu Station (KTX high-speed train from Seoul 2 hours or Busan 40 minutes) at 2:00 PM. Guide welcomes and transfers to 4-star hotel in Dongseongno area, Daegu\'s main shopping and entertainment district (15-minute drive). Check-in and freshen up. Begin city exploration at massive Seomun Market, one of Korea\'s oldest and largest traditional markets operating for over 400 years with 4,000+ shops. Navigate the maze of alleyways selling textiles, Korean fabrics, clothing, dried seafood, traditional medicine ingredients, accessories, and street food. Try local specialties: napjak mandu (flat dumplings), tteokbokki (spicy rice cakes), and various Korean snacks. Experience authentic Korean market culture - energetic, colorful, and delicious! Continue to Kim Gwangseok Street, nostalgic alley dedicated to beloved Korean folk singer who was born in Daegu. See murals depicting his life, bronze statues, and small museum. Live street performances often occur here. Evening exploration of Dongseongno Shopping District, bustling pedestrian street filled with fashion stores, cosmetic shops, trendy cafes, restaurants, and entertainment venues. Popular with young Koreans - feel the energetic youth culture. Welcome dinner at famous Daegu makchang (grilled intestines) restaurant - local specialty not for faint-hearted but delicious! Or choose Korean BBQ option. Return to hotel, evening free for cafe hopping or nightlife.',
        
        'Day 2 - Heritage & Mountain Views' => 'Morning visit (9:00 AM) to Yangnyeongsi Oriental Medicine Cultural Center and Museum, unique attraction showcasing Daegu\'s 350-year history as Korea\'s center for traditional medicine. Learn about Korean herbal medicine (hanyak), see medicinal herbs, understand diagnosis methods, try foot baths with herbal water, and get free health consultation based on traditional Eastern medicine principles. Walk through Yangnyeongsi Medicine Alley where dozens of shops sell ginseng, dried herbs, and traditional remedies. Continue to nearby Daegu Modern History Streets, preserved colonial-era buildings, former missionary houses, churches, and museums telling stories of Korea\'s modernization period and Daegu\'s role in independence movement. Visit Gyesan Catholic Cathedral built 1902. Lunch at traditional Korean restaurant in Jungangno area. Afternoon drive (30 minutes) to Apsan Park, mountain park surrounding Daegu offering spectacular city views. Take cable car to observatory at 500 meters elevation for 360-degree panorama of entire Daegu metropolitan basin surrounded by mountains - stunning vista! Option to hike trails or visit nearby Gatbawi Buddha statue. Gatbawi is famous 9th-century stone Buddha on Palgongsan Mountain (40-minute drive) - legend says Buddha grants one sincere wish, popular with students praying for exam success. Return to city. Dinner on own with guide\'s recommendations.',
        
        'Day 3 - Theme Parks & Tower Views' => 'Fun-filled day starting with visit to Duryu Park (10:00 AM), Daegu\'s largest urban park featuring gardens, walking trails, and Woobang Tower Land (older amusement park). Main attraction: E-World Theme Park, modern amusement park with exciting rides, beautiful gardens, seasonal festivals, and iconic 83 Tower. Spend afternoon enjoying roller coasters, drop towers, music shows, and exploring themed areas. Park is especially beautiful during spring with cherry blossoms or autumn with fall colors. Lunch at park restaurants (various options available). Continue fun at E-World until evening. As darkness falls, ascend the 83 Tower (202 meters tall, named for 1983 completion year), Daegu\'s landmark observation tower offering spectacular night panorama of Daegu cityscape with millions of lights. Enjoy Sky Lounge cafe at tower. Walk around illuminated E-World at night - romantic and magical with colorful lights and fountains. Special farewell dinner at downtown Daegu featuring chimaek (Korean fried chicken and beer) - Daegu specialty! Or choose upscale Korean restaurant. Evening option: explore Daegu\'s famous nightlife in Suseong Lake area (romantic lakeside with cafes and duck-boat rides) or Rodeo Street (youthful club and bar district).',
        
        'Day 4 - Cultural Exploration & Departure' => 'Free morning based on departure schedule and personal interests. Recommendations for optional activities: Visit National Debt Repayment Movement Memorial Hall learning about Daegu citizens\' heroic effort in 1907 to save Korea. Explore Daegu Art Museum with contemporary Korean art. Walk through Gyeongsan Yeongnam University campus area (trendy student district). Shop at Dongdaegu Complex shopping mall. Visit Bangcheon Market for agricultural products and food. Relax at Korean spa (jjimjilbang) for massage and sauna. Browse boutique cafes in Suseong-gu district. Buy local souvenirs: Daegu apples (in season), traditional fabrics, oriental medicine products. Check-out at 12:00 PM. Quick lunch at famous Dongin-dong jjimdak (braised chicken) alley - Daegu food specialty! Transfer to Daegu Station for 5:00 PM or later departure via KTX train to Seoul/Busan. Alternative: Continue to nearby Gyeongju (1-hour drive) for extended trip. Safe journey home with authentic Korean urban experience!',
      ]),
      'arrival' => 'Pick-up at Daegu Station (KTX terminal, connected to East Daegu Station) at 2:00 PM on Day 1. Guide will wait at main exit with "ACP Tours - Daegu" sign. Please book KTX train from Seoul Station (depart 11:30 AM, 2 hours, ₩50,000) or Busan Station (depart 1:00 PM, 40 minutes, ₩15,000). Train tickets not included. Provide train details 2 days before tour. Alternative meeting: Dongdaegu Station or Daegu Airport. Contact: +82-53-XXX-XXXX',
      'departure' => 'Check-out 12:00 PM on Day 4. Transfer to Daegu Station for 5:00 PM or later KTX departure. Recommend booking 6:00 PM or 7:00 PM train for comfortable timing. Seoul-bound trains depart every 30 minutes. Bus to Seoul also available from Express Bus Terminal (4 hours, ₩25,000). Luggage storage at station if needed.',
      'tnc' => 'BOOKING: Minimum 2 people required. Suitable for all ages and fitness levels. PAYMENT: 30% deposit at booking, full payment 7 days before departure. CANCELLATION: 7+ days: 75% refund. 3-6 days: 50% refund. Less than 3 days: No refund. THEME PARK: E-World entrance fee NOT included (₩40,000-55,000 depending on season, includes 83 Tower). Purchase at gate or pre-book for discount. Park closed on some weekdays in winter. WEATHER: Most activities indoor/outdoor mix - tour operates rain or shine. Summer (June-August) very hot in Daegu (30-35°C), bring sunscreen and hat. FOOD: Daegu specialties can be spicy and adventurous (intestines, chicken feet) - alternative options always available. Vegetarian meals possible with 3-day advance notice. SHOPPING: Seomun Market and Dongseongno offer excellent Korean fashion and cosmetics at lower prices than Seoul. Bargaining possible at traditional markets. PEAK SEASON: Daegu Chimac (Chicken & Beer) Festival in July - book accommodations early if attending.',
      'include' => '3 nights accommodation at 4-star hotel Dongseongno central area (twin sharing, modern rooms). Daily breakfast buffet (Western and Korean options). Round-trip transfers between Daegu Station and hotel. Professional English-speaking tour guide Days 1-4. Transportation: comfortable air-conditioned vehicle throughout tour. Entrance fees: Yangnyeongsi Museum, Apsan cable car, 83 Tower observatory (if E-World not entered). 2 group dinners (Day 1 welcome dinner, Day 3 chimaek farewell dinner). Bottled water during tours. Daegu city map and shopping guidebook. Cashbee transport card with ₩8,000 credit.',
      'exclude' => 'KTX train tickets to/from Daegu (Seoul-Daegu ₩50,000 each way, Busan-Daegu ₩15,000 each way - book at letskorail.com). Travel and medical insurance. Lunch all days (estimate ₩10,000-15,000 per meal). Dinner Day 2 (own arrangement). E-World Theme Park entrance (₩40,000-55,000 includes 83 Tower) OR separate 83 Tower only ticket (₩10,000). Optional activities: Woobang Tower Land ₩20,000, Suseong Lake duck-boat rides ₩15,000, spa/jjimjilbang ₩12,000, additional museums, cooking class. Personal expenses, shopping, souvenirs. Gatbawi Buddha site donation (suggested ₩5,000). Tips for guide and driver (suggest ₩45,000 per person total). Single room supplement ₩700,000 total. Nightclub or bar entrance fees. Any items not in inclusions.',
      'nearby_hotel' => 'Inter-Burgo Exco Daegu (5-star convention hotel), Novotel Ambassador Daegu (4-star international chain), Hotel Susung (boutique with spa), Eldis Regent Hotel (business hotel), Hotel Ariana (modern mid-range), Daegu Grand Hotel (affordable near station), Benikea Jungangno Hotel (budget-friendly central), Goodstay Hotel (economy option)',
      'map_url' => 'https://www.google.com/maps/place/Daegu,+South+Korea/@35.8714,128.6014,11z',
    ]);

    $daeguPhotos = [
      'destinations/daegu-photo-1.jpg',
      'destinations/daegu-photo-2.jpg',
      'destinations/daegu-photo-3.jpg',
    ];

    foreach ($daeguPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $daegu->id,
        'photo' => $photo,
      ]);
    }

    $jeonju = Destination::create([
      'title' => 'Jeonju Hanok Heritage - 3D2N Traditional Living',
      'slug' => 'jeonju-hanok-village-experience',
      'description' => 'Step back in time and experience authentic Korean traditions in Jeonju, the spiritual capital of Korean culture and birthplace of the Joseon Dynasty. This immersive 3-day cultural journey centers on Jeonju Hanok Village, Korea\'s largest collection of over 700 traditional hanok houses where locals still live, work, and preserve centuries-old customs. Sleep on warm ondol floors in authentic hanok accommodation, taste the original Jeonju bibimbap (considered Korea\'s finest), learn traditional crafts like hanji papermaking and fan painting, wear beautiful hanbok through historic streets, visit important Joseon Dynasty shrines, explore living museums of traditional music and alcohol, wander through atmospheric alleyways lined with craft shops and tea houses, and discover why UNESCO named Jeonju a City of Gastronomy. Perfect for culture lovers, food enthusiasts, photographers, families, and anyone seeking deep immersion in Korean heritage and traditional lifestyle.',
      'country' => 'South Korea',
      'city' => 'Jeonju',
      'price' => 4800000,
      'date_started' => '2026-06-01',
      'date_ended' => '2026-06-03',
      'type' => 'Cultural Immersion',
      'view_count' => 130,
      'featured_photo' => 'destinations/jeonju-featured.jpg',
      'min_people' => 2,
      'max_people' => 12,
    ]);

    DestinationDetail::create([
      'destination_id' => $jeonju->id,
      'itinerary' => json_encode([
        'Day 1 - Hanok Village & Culinary Heritage' => 'Arrive at Jeonju Express Bus Terminal (2.5 hours from Seoul, 2 hours from Busan) at 12:00 PM. Guide warmly welcomes you to Jeonju, spiritual home of Korean culture. Transfer to traditional hanok guesthouse inside historic Jeonju Hanok Village (10-minute drive). Check-in to beautifully preserved Korean traditional house featuring curved tile roofs, wooden beams, paper doors (hanji), and heated ondol floors for sleeping on traditional futon bedding - authentic experience! Change into complimentary hanbok (traditional Korean costume) included for entire stay - wear it throughout village for free entry to attractions and countless photo opportunities. Look like Korean royalty! Begin exploration of enchanting Hanok Village, a living community of 700+ traditional houses where residents maintain age-old customs. Visit Gyeonggijeon Shrine, sacred repository housing portrait of King Taejo, founder of Joseon Dynasty born in Jeonju. See beautifully maintained traditional architecture and royal gardens. Continue to Jeondong Catholic Cathedral, stunning Romanesque building from 1914 blending Western and Korean architectural elements. Walk through picturesque alleyways discovering hidden cafes, craft shops, and galleries. Lunch at famous Jeonju bibimbap restaurant - taste Korea\'s most celebrated dish in its birthplace! Authentic Jeonju bibimbap features 30+ seasonal ingredients in brass bowl with raw beef, perfect rice, and gochujang (red pepper paste). Evening participation in traditional Korean cooking class - learn to make bibimbap, pajeon (Korean pancake), and makgeolli (rice wine). Enjoy dinner with dishes you prepared! Return to hanok for traditional tea ceremony and evening walk through lantern-lit village streets - magical atmosphere. Sleep on warm ondol floors.',

        'Day 2 - Traditional Crafts & Living Culture' => 'Wake to sounds of traditional village life. Breakfast at hanok featuring Korean temple food or traditional meal. Morning dedicated to hands-on cultural experiences. Start at Traditional Korean Paper (Hanji) Workshop - learn ancient art of making Korean paper from mulberry bark. Create your own hanji bookmark or art piece to take home. Continue to Fan Painting Workshop - paint traditional Korean motifs (flowers, birds, landscapes) on Korean fan using traditional brushes and inks under master artist guidance. Visit Traditional Wine Museum (Jeonju Bibimbap Village) learning about makgeolli brewing and Korean alcohol culture - tasting included for adults! Explore Jeonju Traditional Culture Center witnessing traditional crafts being made: embroidery, mother-of-pearl lacquerware, woodcraft. Lunch at traditional Korean restaurant in hanok setting. Afternoon visit to Korean Traditional Music (Pansori) Museum - learn about this UNESCO Intangible Cultural Heritage oral narrative singing tradition. Possible live performance if schedule permits. Walk to Omokdae and Imokdae Pavilions, elevated historical sites offering best panoramic views of entire Hanok Village with sea of traditional curved tile roofs - spectacular photo moment especially at golden hour! These pavilions mark where Taejo celebrated founding of Joseon Dynasty. Free time to explore village\'s many treasures: browse traditional craft shops selling hanji products, Korean fans, pottery, tea sets. Try Jeonju\'s famous street snacks: chocopie (chocolate-covered red bean cake), choco banana, Korean traditional sweets. Evening special farewell dinner: Jeonju hanjeongsik, elaborate traditional Korean full-course meal with 20-30+ small dishes showcasing local ingredients and royal cuisine traditions - unforgettable feast! Vegetarian temple food hanjeongsik available. Final night in cozy hanok.',

        'Day 3 - Heritage Sites & Departure' => 'Final morning in traditional house. Breakfast at hanok. Free time for last explorations based on interests and departure schedule. Recommendations: Visit Jeonju Hanok Living Experience Center for more cultural activities, explore Nambu Traditional Market for local ingredients and street food, shop for souvenirs (hanji products, traditional fans, Korean tea, gochujang, traditional sweets), revisit favorite spots for better photos in hanbok, relax at traditional tea house, or simply wander atmospheric alleyways discovering hidden corners. Late morning visit to Pungnammun Gate, one of Korea\'s largest traditional city gates from 1398 and symbol of Jeonju. Check-out from hanok at 12:00 PM (return hanbok). Quick visit to nearby Jeonju Hanji Museum if time permits, showcasing history and art of Korean traditional paper. Farewell lunch featuring Jeonju\'s another specialty: kongnamul gukbap (bean sprout soup with rice) - simple but deeply flavorful comfort food perfect before journey. Transfer to Jeonju Express Bus Terminal for 4:00 PM or later departure. Alternative: extend trip by visiting nearby Maisan Mountain (unique twin peaks) or continue to Gunsan Port City (40 minutes). Return home with heart full of Korean traditions, skills in traditional crafts, belly full of amazing food, memory card full of hanbok photos, and deep appreciation for Korean cultural heritage!',
      ]),
      'arrival' => 'Pick-up at Jeonju Express Bus Terminal at 12:00 PM on Day 1. Guide will wait at main exit gate with "ACP Tours - Jeonju" sign. Please book express bus from Seoul Express Bus Terminal (depart 9:30 AM, 2.5 hours, ₩15,000) or Busan (depart 10:00 AM, 2 hours, ₩18,000). Bus tickets not included - book at www.kobus.co.kr. Alternative: KTX train to Iksan Station (1.5 hours from Seoul) then local bus/taxi to Jeonju (30 minutes). Provide arrival details 2 days before tour. Contact: +82-63-XXX-XXXX',
      'departure' => 'Check-out from hanok at 12:00 PM on Day 3 (flexible based on guesthouse). Transfer to Jeonju Express Bus Terminal for 4:00 PM or later bus to Seoul/Busan. Recommend 5:00 PM or 6:00 PM bus for comfortable timing. Bus frequency every hour. Alternative drop-off at Jeonju Station for train connections. Taxi to Iksan KTX Station can be arranged (30 minutes, ₩30,000).',
      'tnc' => 'BOOKING & ACCOMMODATION: Minimum 2 people required. Accommodation in traditional hanok guesthouse - authentic experience with ondol floor sleeping (futon bedding), shared bathroom facilities in some hanoks, traditional architecture. Not luxury hotel - cultural immersion priority. Modern hotel upgrade available at additional cost. PAYMENT: 30% deposit at booking, full payment 7 days before tour. CANCELLATION: 7+ days: 80% refund. 4-6 days: 60% refund. Less than 4 days: No refund. HANBOK RENTAL: Included for all 3 days (entire stay) - wear throughout village. Many photo spots! Proper hanbok etiquette taught. CRAFT WORKSHOPS: Hanji paper-making and fan painting included. Additional craft workshops available at extra cost (embroidery, pottery, natural dyeing). DIETARY: Jeonju food culture is bibimbap, makgeolli, traditional meals - vegetarian modifications available with 5-day advance notice. Temple food options available. SPECIAL: Jeonju International Sori Festival (October) features traditional music performances - highly recommended but book early. Jeonju Film Festival (April-May) brings increased crowds. CULTURAL RESPECT: Hanok Village is residential community - respect residents\' privacy. Remove shoes when entering buildings. Photography permitted but ask permission for resident photos.',
      'include' => '2 nights accommodation in traditional hanok guesthouse inside Hanok Village (twin/family room sharing, ondol floor sleeping with futon). Daily breakfast (Korean-style traditional meal). All meals included: 2 lunches (Day 1 authentic Jeonju bibimbap, Day 3 kongnamul gukbap), 2 dinners (Day 1 cooking class meal, Day 2 hanjeongsik farewell dinner). Round-trip transfers between Jeonju Bus Terminal and hanok. Professional English-speaking cultural guide all 3 days. Hanbok (traditional costume) rental for entire stay (3 days) - wear throughout village. Entrance fees: Gyeonggijeon Shrine, Jeondong Cathedral, Traditional Wine Museum, Pansori Museum. Traditional Korean cooking class Day 1 (bibimbap, pajeon, makgeolli). Hands-on cultural workshops: Hanji paper-making, traditional fan painting. Makgeolli tasting at Wine Museum (adults only). Traditional tea ceremony Day 1. All materials for craft workshops. Jeonju Hanok Village map and cultural guidebook. Traditional Korean souvenir (hanji product or fan you created).',
      'exclude' => 'Express bus tickets to/from Jeonju (Seoul-Jeonju ₩15,000 each way, Busan-Jeonju ₩18,000 each way - book at kobus.co.kr). Train tickets if using KTX via Iksan. Travel and medical insurance. Personal expenses, shopping, souvenirs beyond included items. Optional additional craft workshops (pottery ₩30,000, natural dyeing ₩25,000, embroidery ₩35,000, traditional knot-making ₩20,000). Modern hotel upgrade (4-star hotel instead of hanok, add ₩600,000 per person). Street food and snacks in village. Additional hanbok rental for different styles/upgrades. Tips for guide (suggest ₩35,000 per person total for 3 days). Private hanok room upgrade if available (₩400,000 total). Any items not mentioned in inclusions. Traditional performance tickets if available.',
      'nearby_hotel' => 'Ramada Jeonju Hotel (4-star modern near Hanok Village), Korea Traditional Hotel (upscale hanok-style), Jeonju Hanok Village Guesthouses (various traditional options inside village), Core Ciel Hotel Jeonju (mid-range modern), Jeonju Hue Stay (boutique guesthouse), Han Sung Heritage House (premium hanok), Best Western Jeonju (international chain), Traditional Hanok Minbak (budget-friendly hanok stays)',
      'map_url' => 'https://www.google.com/maps/place/Jeonju+Hanok+Village,+Jeonju,+South+Korea/@35.8144,127.1522,15z',
    ]);

    $jeonjuPhotos = [
      'destinations/jeonju-photo-1.jpg',
      'destinations/jeonju-photo-2.jpg',
      'destinations/jeonju-photo-3.jpg',
      'destinations/jeonju-photo-4.jpg',
    ];

    foreach ($jeonjuPhotos as $photo) {
      DestinationPhoto::create([
        'destination_id' => $jeonju->id,
        'photo' => $photo,
      ]);
    }
  }
}